config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :rooftops
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rooftop.rb
class Rooftop < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/rooftops_controller.rb
class RooftopsController < ApplicationController
  before_action :set_rooftop, only: [:show, :edit, :update, :destroy]

  def index
    @rooftops = Rooftop.all
  end

  def show; end

  def new
    @rooftop = Rooftop.new
  end

  def create
    @rooftop = Rooftop.new(rooftop_params)
    if @rooftop.save
      redirect_to rooftop_path(@rooftop)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @rooftop.update(rooftop_params)
      redirect_to rooftop_path(@rooftop)
    else
      render :edit
    end
  end

  def destroy
    @rooftop.destroy
    redirect_to rooftops_path
  end

  private

  def set_rooftop
    @rooftop = Rooftop.find(params[:id])
  end

  def rooftop_params
    params.require(:rooftop).permit(:name, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= content_for?(:title) ? yield(:title) : Rooftop %></title>
    <%= favicon_link_tag asset_path('terrace_turquoise.png') %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <% if controller.controller_name == "pages" && controller.action_name == "home" %>
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0)), url(https://images.unsplash.com/photo-1559339352-11d035aa65de?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80);">
        <%= render "shared/navbar" %>
        <div class="container homepage">
          <h1>Rent a rooftop, terrace or patio anywhere</h1>
          <p><span id="banner-typed-text"></span></p>
          <%= link_to "Find a rooftop!", rooftops_path, {class: "btn btn-primary"} %>
        </div>
      </div>
    <% else %>
      <%= render "shared/navbar" %>
    <% end %>

    <%= render "shared/flashes" %>
    <%= yield %>
    <%#= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/rooftops/_card.html.erb
<%= link_to rooftop_path(rooftop), {class: "show-link"} do %>
  <div class="card-rooftop">
    <img src="https://images.unsplash.com/photo-1559339352-11d035aa65de?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80" />
    <div class="card-rooftop-infos">
      <div>
        <h2><%= rooftop.name %></h2>
        <p><%= rooftop.description %></p>
      </div>
      <h2 class="card-rooftop-pricing"><%= rooftop.price %>€</h2>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-rooftop-user avatar-bordered" />
    </div>
  </div>
<% end %>

app/views/rooftops/_form.html.erb
<%= form_for(@rooftop) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/rooftops/_rooftop.html.erb
<div class="col-sm-4">
<%= link_to rooftop_path(rooftop), {class: "show-link"} do %>
  <div class="card-rooftop">
    <img src="https://images.unsplash.com/photo-1559339352-11d035aa65de?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80" />
    <div class="card-rooftop-infos">
      <div>
        <h2><%= rooftop.name %></h2>
        <p><%= rooftop.description %></p>
      </div>
      <h2 class="card-rooftop-pricing"><%= rooftop.price %>€</h2>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-rooftop-user avatar-bordered" />
    </div>
  </div>
<% end %>
</div>

app/views/rooftops/edit.html.erb
<% content_for(:title) do %>
  Edit <%= @rooftop.name %>
<% end %>

<%= render 'form', rooftop: @rooftop %>

app/views/rooftops/index.html.erb
<% content_for(:title) do %>
  All rooftops
<% end %>

<div class="container">
  <div class="row rooftop-cards">
    <%= render @rooftops  %>
    <%# @rooftops.each do |r| %>
      <!-- <div class="col-sm-4"> -->
        <%#= render "card", rooftop: r %>
      <!-- </div> -->
    <%# end %>
  </div>
</div>

app/views/rooftops/new.html.erb
<% content_for(:title) do %>
  Create a new rooftop
<% end %>

<%= render 'form', rooftop: @rooftop %>

app/views/rooftops/show.html.erb
<% content_for(:title) do %>
  <%= @rooftop.name %>
<% end %>

<div class="container">

<div class="show-banner">
<h2><%= @rooftop.name %></h2>
<p><%= @rooftop.description %></p>

</div>

<%= link_to "Delete", rooftop_path(@rooftop),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if controller.controller_name == "pages" && controller.action_name == "home" %>
  <div class="navbar navbar-expand-sm navbar-lewagon navbar-fixed-top transparent">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "terrace_white.png" %>
      <% end %>
  </div>
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-fixed-top fixed-top">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "terrace_turquoise.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "See all rooftops", rooftops_path, class: "btn btn-primary mr-3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Rent a rooftop", new_rooftop_path, class: "btn btn-ghost mr-3" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My Dashboard", "#", class: "dropdown-item" %>
              <%#= link_to "See all rooftops", rooftops_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>